restore_step: 30000
speaker_id: 0
configModels: 
  preprocess_config: 'config/Viet_tts/preprocess.yaml'
  model_config: 'config/Viet_tts/model.yaml'
  train_config: 'config/Viet_tts/train.yaml'
control_values:
  pitch_control: 1.0
  energy_control: 1.0
  duration_control: 1.0